# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vol/d/development/git/mCAAT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vol/d/development/git/mCAAT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/d/development/git/mCAAT/CMakeFiles /vol/d/development/git/mCAAT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/d/development/git/mCAAT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcaat

# Build rule for target.
mcaat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcaat
.PHONY : mcaat

# fast build rule for target.
mcaat/fast:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/build
.PHONY : mcaat/fast

libs/megahit/src/assembly/bubble_remover.o: libs/megahit/src/assembly/bubble_remover.cpp.o

.PHONY : libs/megahit/src/assembly/bubble_remover.o

# target to build an object file
libs/megahit/src/assembly/bubble_remover.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/bubble_remover.cpp.o
.PHONY : libs/megahit/src/assembly/bubble_remover.cpp.o

libs/megahit/src/assembly/bubble_remover.i: libs/megahit/src/assembly/bubble_remover.cpp.i

.PHONY : libs/megahit/src/assembly/bubble_remover.i

# target to preprocess a source file
libs/megahit/src/assembly/bubble_remover.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/bubble_remover.cpp.i
.PHONY : libs/megahit/src/assembly/bubble_remover.cpp.i

libs/megahit/src/assembly/bubble_remover.s: libs/megahit/src/assembly/bubble_remover.cpp.s

.PHONY : libs/megahit/src/assembly/bubble_remover.s

# target to generate assembly for a file
libs/megahit/src/assembly/bubble_remover.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/bubble_remover.cpp.s
.PHONY : libs/megahit/src/assembly/bubble_remover.cpp.s

libs/megahit/src/assembly/contig_output.o: libs/megahit/src/assembly/contig_output.cpp.o

.PHONY : libs/megahit/src/assembly/contig_output.o

# target to build an object file
libs/megahit/src/assembly/contig_output.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/contig_output.cpp.o
.PHONY : libs/megahit/src/assembly/contig_output.cpp.o

libs/megahit/src/assembly/contig_output.i: libs/megahit/src/assembly/contig_output.cpp.i

.PHONY : libs/megahit/src/assembly/contig_output.i

# target to preprocess a source file
libs/megahit/src/assembly/contig_output.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/contig_output.cpp.i
.PHONY : libs/megahit/src/assembly/contig_output.cpp.i

libs/megahit/src/assembly/contig_output.s: libs/megahit/src/assembly/contig_output.cpp.s

.PHONY : libs/megahit/src/assembly/contig_output.s

# target to generate assembly for a file
libs/megahit/src/assembly/contig_output.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/contig_output.cpp.s
.PHONY : libs/megahit/src/assembly/contig_output.cpp.s

libs/megahit/src/assembly/low_depth_remover.o: libs/megahit/src/assembly/low_depth_remover.cpp.o

.PHONY : libs/megahit/src/assembly/low_depth_remover.o

# target to build an object file
libs/megahit/src/assembly/low_depth_remover.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/low_depth_remover.cpp.o
.PHONY : libs/megahit/src/assembly/low_depth_remover.cpp.o

libs/megahit/src/assembly/low_depth_remover.i: libs/megahit/src/assembly/low_depth_remover.cpp.i

.PHONY : libs/megahit/src/assembly/low_depth_remover.i

# target to preprocess a source file
libs/megahit/src/assembly/low_depth_remover.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/low_depth_remover.cpp.i
.PHONY : libs/megahit/src/assembly/low_depth_remover.cpp.i

libs/megahit/src/assembly/low_depth_remover.s: libs/megahit/src/assembly/low_depth_remover.cpp.s

.PHONY : libs/megahit/src/assembly/low_depth_remover.s

# target to generate assembly for a file
libs/megahit/src/assembly/low_depth_remover.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/low_depth_remover.cpp.s
.PHONY : libs/megahit/src/assembly/low_depth_remover.cpp.s

libs/megahit/src/assembly/sdbg_pruning.o: libs/megahit/src/assembly/sdbg_pruning.cpp.o

.PHONY : libs/megahit/src/assembly/sdbg_pruning.o

# target to build an object file
libs/megahit/src/assembly/sdbg_pruning.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/sdbg_pruning.cpp.o
.PHONY : libs/megahit/src/assembly/sdbg_pruning.cpp.o

libs/megahit/src/assembly/sdbg_pruning.i: libs/megahit/src/assembly/sdbg_pruning.cpp.i

.PHONY : libs/megahit/src/assembly/sdbg_pruning.i

# target to preprocess a source file
libs/megahit/src/assembly/sdbg_pruning.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/sdbg_pruning.cpp.i
.PHONY : libs/megahit/src/assembly/sdbg_pruning.cpp.i

libs/megahit/src/assembly/sdbg_pruning.s: libs/megahit/src/assembly/sdbg_pruning.cpp.s

.PHONY : libs/megahit/src/assembly/sdbg_pruning.s

# target to generate assembly for a file
libs/megahit/src/assembly/sdbg_pruning.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/sdbg_pruning.cpp.s
.PHONY : libs/megahit/src/assembly/sdbg_pruning.cpp.s

libs/megahit/src/assembly/tip_remover.o: libs/megahit/src/assembly/tip_remover.cpp.o

.PHONY : libs/megahit/src/assembly/tip_remover.o

# target to build an object file
libs/megahit/src/assembly/tip_remover.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/tip_remover.cpp.o
.PHONY : libs/megahit/src/assembly/tip_remover.cpp.o

libs/megahit/src/assembly/tip_remover.i: libs/megahit/src/assembly/tip_remover.cpp.i

.PHONY : libs/megahit/src/assembly/tip_remover.i

# target to preprocess a source file
libs/megahit/src/assembly/tip_remover.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/tip_remover.cpp.i
.PHONY : libs/megahit/src/assembly/tip_remover.cpp.i

libs/megahit/src/assembly/tip_remover.s: libs/megahit/src/assembly/tip_remover.cpp.s

.PHONY : libs/megahit/src/assembly/tip_remover.s

# target to generate assembly for a file
libs/megahit/src/assembly/tip_remover.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/tip_remover.cpp.s
.PHONY : libs/megahit/src/assembly/tip_remover.cpp.s

libs/megahit/src/assembly/unitig_graph.o: libs/megahit/src/assembly/unitig_graph.cpp.o

.PHONY : libs/megahit/src/assembly/unitig_graph.o

# target to build an object file
libs/megahit/src/assembly/unitig_graph.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/unitig_graph.cpp.o
.PHONY : libs/megahit/src/assembly/unitig_graph.cpp.o

libs/megahit/src/assembly/unitig_graph.i: libs/megahit/src/assembly/unitig_graph.cpp.i

.PHONY : libs/megahit/src/assembly/unitig_graph.i

# target to preprocess a source file
libs/megahit/src/assembly/unitig_graph.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/unitig_graph.cpp.i
.PHONY : libs/megahit/src/assembly/unitig_graph.cpp.i

libs/megahit/src/assembly/unitig_graph.s: libs/megahit/src/assembly/unitig_graph.cpp.s

.PHONY : libs/megahit/src/assembly/unitig_graph.s

# target to generate assembly for a file
libs/megahit/src/assembly/unitig_graph.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/unitig_graph.cpp.s
.PHONY : libs/megahit/src/assembly/unitig_graph.cpp.s

libs/megahit/src/assembly/weak_link_remover.o: libs/megahit/src/assembly/weak_link_remover.cpp.o

.PHONY : libs/megahit/src/assembly/weak_link_remover.o

# target to build an object file
libs/megahit/src/assembly/weak_link_remover.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/weak_link_remover.cpp.o
.PHONY : libs/megahit/src/assembly/weak_link_remover.cpp.o

libs/megahit/src/assembly/weak_link_remover.i: libs/megahit/src/assembly/weak_link_remover.cpp.i

.PHONY : libs/megahit/src/assembly/weak_link_remover.i

# target to preprocess a source file
libs/megahit/src/assembly/weak_link_remover.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/weak_link_remover.cpp.i
.PHONY : libs/megahit/src/assembly/weak_link_remover.cpp.i

libs/megahit/src/assembly/weak_link_remover.s: libs/megahit/src/assembly/weak_link_remover.cpp.s

.PHONY : libs/megahit/src/assembly/weak_link_remover.s

# target to generate assembly for a file
libs/megahit/src/assembly/weak_link_remover.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/assembly/weak_link_remover.cpp.s
.PHONY : libs/megahit/src/assembly/weak_link_remover.cpp.s

libs/megahit/src/idba/contig_graph.o: libs/megahit/src/idba/contig_graph.cpp.o

.PHONY : libs/megahit/src/idba/contig_graph.o

# target to build an object file
libs/megahit/src/idba/contig_graph.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph.cpp.o
.PHONY : libs/megahit/src/idba/contig_graph.cpp.o

libs/megahit/src/idba/contig_graph.i: libs/megahit/src/idba/contig_graph.cpp.i

.PHONY : libs/megahit/src/idba/contig_graph.i

# target to preprocess a source file
libs/megahit/src/idba/contig_graph.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph.cpp.i
.PHONY : libs/megahit/src/idba/contig_graph.cpp.i

libs/megahit/src/idba/contig_graph.s: libs/megahit/src/idba/contig_graph.cpp.s

.PHONY : libs/megahit/src/idba/contig_graph.s

# target to generate assembly for a file
libs/megahit/src/idba/contig_graph.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph.cpp.s
.PHONY : libs/megahit/src/idba/contig_graph.cpp.s

libs/megahit/src/idba/contig_graph_branch_group.o: libs/megahit/src/idba/contig_graph_branch_group.cpp.o

.PHONY : libs/megahit/src/idba/contig_graph_branch_group.o

# target to build an object file
libs/megahit/src/idba/contig_graph_branch_group.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph_branch_group.cpp.o
.PHONY : libs/megahit/src/idba/contig_graph_branch_group.cpp.o

libs/megahit/src/idba/contig_graph_branch_group.i: libs/megahit/src/idba/contig_graph_branch_group.cpp.i

.PHONY : libs/megahit/src/idba/contig_graph_branch_group.i

# target to preprocess a source file
libs/megahit/src/idba/contig_graph_branch_group.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph_branch_group.cpp.i
.PHONY : libs/megahit/src/idba/contig_graph_branch_group.cpp.i

libs/megahit/src/idba/contig_graph_branch_group.s: libs/megahit/src/idba/contig_graph_branch_group.cpp.s

.PHONY : libs/megahit/src/idba/contig_graph_branch_group.s

# target to generate assembly for a file
libs/megahit/src/idba/contig_graph_branch_group.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/contig_graph_branch_group.cpp.s
.PHONY : libs/megahit/src/idba/contig_graph_branch_group.cpp.s

libs/megahit/src/idba/hash_graph.o: libs/megahit/src/idba/hash_graph.cpp.o

.PHONY : libs/megahit/src/idba/hash_graph.o

# target to build an object file
libs/megahit/src/idba/hash_graph.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/hash_graph.cpp.o
.PHONY : libs/megahit/src/idba/hash_graph.cpp.o

libs/megahit/src/idba/hash_graph.i: libs/megahit/src/idba/hash_graph.cpp.i

.PHONY : libs/megahit/src/idba/hash_graph.i

# target to preprocess a source file
libs/megahit/src/idba/hash_graph.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/hash_graph.cpp.i
.PHONY : libs/megahit/src/idba/hash_graph.cpp.i

libs/megahit/src/idba/hash_graph.s: libs/megahit/src/idba/hash_graph.cpp.s

.PHONY : libs/megahit/src/idba/hash_graph.s

# target to generate assembly for a file
libs/megahit/src/idba/hash_graph.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/hash_graph.cpp.s
.PHONY : libs/megahit/src/idba/hash_graph.cpp.s

libs/megahit/src/idba/sequence.o: libs/megahit/src/idba/sequence.cpp.o

.PHONY : libs/megahit/src/idba/sequence.o

# target to build an object file
libs/megahit/src/idba/sequence.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/sequence.cpp.o
.PHONY : libs/megahit/src/idba/sequence.cpp.o

libs/megahit/src/idba/sequence.i: libs/megahit/src/idba/sequence.cpp.i

.PHONY : libs/megahit/src/idba/sequence.i

# target to preprocess a source file
libs/megahit/src/idba/sequence.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/sequence.cpp.i
.PHONY : libs/megahit/src/idba/sequence.cpp.i

libs/megahit/src/idba/sequence.s: libs/megahit/src/idba/sequence.cpp.s

.PHONY : libs/megahit/src/idba/sequence.s

# target to generate assembly for a file
libs/megahit/src/idba/sequence.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/idba/sequence.cpp.s
.PHONY : libs/megahit/src/idba/sequence.cpp.s

libs/megahit/src/localasm/hash_mapper.o: libs/megahit/src/localasm/hash_mapper.cpp.o

.PHONY : libs/megahit/src/localasm/hash_mapper.o

# target to build an object file
libs/megahit/src/localasm/hash_mapper.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/hash_mapper.cpp.o
.PHONY : libs/megahit/src/localasm/hash_mapper.cpp.o

libs/megahit/src/localasm/hash_mapper.i: libs/megahit/src/localasm/hash_mapper.cpp.i

.PHONY : libs/megahit/src/localasm/hash_mapper.i

# target to preprocess a source file
libs/megahit/src/localasm/hash_mapper.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/hash_mapper.cpp.i
.PHONY : libs/megahit/src/localasm/hash_mapper.cpp.i

libs/megahit/src/localasm/hash_mapper.s: libs/megahit/src/localasm/hash_mapper.cpp.s

.PHONY : libs/megahit/src/localasm/hash_mapper.s

# target to generate assembly for a file
libs/megahit/src/localasm/hash_mapper.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/hash_mapper.cpp.s
.PHONY : libs/megahit/src/localasm/hash_mapper.cpp.s

libs/megahit/src/localasm/local_assemble.o: libs/megahit/src/localasm/local_assemble.cpp.o

.PHONY : libs/megahit/src/localasm/local_assemble.o

# target to build an object file
libs/megahit/src/localasm/local_assemble.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/local_assemble.cpp.o
.PHONY : libs/megahit/src/localasm/local_assemble.cpp.o

libs/megahit/src/localasm/local_assemble.i: libs/megahit/src/localasm/local_assemble.cpp.i

.PHONY : libs/megahit/src/localasm/local_assemble.i

# target to preprocess a source file
libs/megahit/src/localasm/local_assemble.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/local_assemble.cpp.i
.PHONY : libs/megahit/src/localasm/local_assemble.cpp.i

libs/megahit/src/localasm/local_assemble.s: libs/megahit/src/localasm/local_assemble.cpp.s

.PHONY : libs/megahit/src/localasm/local_assemble.s

# target to generate assembly for a file
libs/megahit/src/localasm/local_assemble.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/localasm/local_assemble.cpp.s
.PHONY : libs/megahit/src/localasm/local_assemble.cpp.s

libs/megahit/src/sdbg/sdbg_meta.o: libs/megahit/src/sdbg/sdbg_meta.cpp.o

.PHONY : libs/megahit/src/sdbg/sdbg_meta.o

# target to build an object file
libs/megahit/src/sdbg/sdbg_meta.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_meta.cpp.o
.PHONY : libs/megahit/src/sdbg/sdbg_meta.cpp.o

libs/megahit/src/sdbg/sdbg_meta.i: libs/megahit/src/sdbg/sdbg_meta.cpp.i

.PHONY : libs/megahit/src/sdbg/sdbg_meta.i

# target to preprocess a source file
libs/megahit/src/sdbg/sdbg_meta.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_meta.cpp.i
.PHONY : libs/megahit/src/sdbg/sdbg_meta.cpp.i

libs/megahit/src/sdbg/sdbg_meta.s: libs/megahit/src/sdbg/sdbg_meta.cpp.s

.PHONY : libs/megahit/src/sdbg/sdbg_meta.s

# target to generate assembly for a file
libs/megahit/src/sdbg/sdbg_meta.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_meta.cpp.s
.PHONY : libs/megahit/src/sdbg/sdbg_meta.cpp.s

libs/megahit/src/sdbg/sdbg_raw_content.o: libs/megahit/src/sdbg/sdbg_raw_content.cpp.o

.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.o

# target to build an object file
libs/megahit/src/sdbg/sdbg_raw_content.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_raw_content.cpp.o
.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.cpp.o

libs/megahit/src/sdbg/sdbg_raw_content.i: libs/megahit/src/sdbg/sdbg_raw_content.cpp.i

.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.i

# target to preprocess a source file
libs/megahit/src/sdbg/sdbg_raw_content.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_raw_content.cpp.i
.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.cpp.i

libs/megahit/src/sdbg/sdbg_raw_content.s: libs/megahit/src/sdbg/sdbg_raw_content.cpp.s

.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.s

# target to generate assembly for a file
libs/megahit/src/sdbg/sdbg_raw_content.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_raw_content.cpp.s
.PHONY : libs/megahit/src/sdbg/sdbg_raw_content.cpp.s

libs/megahit/src/sdbg/sdbg_writer.o: libs/megahit/src/sdbg/sdbg_writer.cpp.o

.PHONY : libs/megahit/src/sdbg/sdbg_writer.o

# target to build an object file
libs/megahit/src/sdbg/sdbg_writer.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_writer.cpp.o
.PHONY : libs/megahit/src/sdbg/sdbg_writer.cpp.o

libs/megahit/src/sdbg/sdbg_writer.i: libs/megahit/src/sdbg/sdbg_writer.cpp.i

.PHONY : libs/megahit/src/sdbg/sdbg_writer.i

# target to preprocess a source file
libs/megahit/src/sdbg/sdbg_writer.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_writer.cpp.i
.PHONY : libs/megahit/src/sdbg/sdbg_writer.cpp.i

libs/megahit/src/sdbg/sdbg_writer.s: libs/megahit/src/sdbg/sdbg_writer.cpp.s

.PHONY : libs/megahit/src/sdbg/sdbg_writer.s

# target to generate assembly for a file
libs/megahit/src/sdbg/sdbg_writer.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sdbg/sdbg_writer.cpp.s
.PHONY : libs/megahit/src/sdbg/sdbg_writer.cpp.s

libs/megahit/src/sequence/io/fastx_reader.o: libs/megahit/src/sequence/io/fastx_reader.cpp.o

.PHONY : libs/megahit/src/sequence/io/fastx_reader.o

# target to build an object file
libs/megahit/src/sequence/io/fastx_reader.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/fastx_reader.cpp.o
.PHONY : libs/megahit/src/sequence/io/fastx_reader.cpp.o

libs/megahit/src/sequence/io/fastx_reader.i: libs/megahit/src/sequence/io/fastx_reader.cpp.i

.PHONY : libs/megahit/src/sequence/io/fastx_reader.i

# target to preprocess a source file
libs/megahit/src/sequence/io/fastx_reader.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/fastx_reader.cpp.i
.PHONY : libs/megahit/src/sequence/io/fastx_reader.cpp.i

libs/megahit/src/sequence/io/fastx_reader.s: libs/megahit/src/sequence/io/fastx_reader.cpp.s

.PHONY : libs/megahit/src/sequence/io/fastx_reader.s

# target to generate assembly for a file
libs/megahit/src/sequence/io/fastx_reader.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/fastx_reader.cpp.s
.PHONY : libs/megahit/src/sequence/io/fastx_reader.cpp.s

libs/megahit/src/sequence/io/paired_fastx_reader.o: libs/megahit/src/sequence/io/paired_fastx_reader.cpp.o

.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.o

# target to build an object file
libs/megahit/src/sequence/io/paired_fastx_reader.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/paired_fastx_reader.cpp.o
.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.cpp.o

libs/megahit/src/sequence/io/paired_fastx_reader.i: libs/megahit/src/sequence/io/paired_fastx_reader.cpp.i

.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.i

# target to preprocess a source file
libs/megahit/src/sequence/io/paired_fastx_reader.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/paired_fastx_reader.cpp.i
.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.cpp.i

libs/megahit/src/sequence/io/paired_fastx_reader.s: libs/megahit/src/sequence/io/paired_fastx_reader.cpp.s

.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.s

# target to generate assembly for a file
libs/megahit/src/sequence/io/paired_fastx_reader.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/paired_fastx_reader.cpp.s
.PHONY : libs/megahit/src/sequence/io/paired_fastx_reader.cpp.s

libs/megahit/src/sequence/io/sequence_lib.o: libs/megahit/src/sequence/io/sequence_lib.cpp.o

.PHONY : libs/megahit/src/sequence/io/sequence_lib.o

# target to build an object file
libs/megahit/src/sequence/io/sequence_lib.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/sequence_lib.cpp.o
.PHONY : libs/megahit/src/sequence/io/sequence_lib.cpp.o

libs/megahit/src/sequence/io/sequence_lib.i: libs/megahit/src/sequence/io/sequence_lib.cpp.i

.PHONY : libs/megahit/src/sequence/io/sequence_lib.i

# target to preprocess a source file
libs/megahit/src/sequence/io/sequence_lib.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/sequence_lib.cpp.i
.PHONY : libs/megahit/src/sequence/io/sequence_lib.cpp.i

libs/megahit/src/sequence/io/sequence_lib.s: libs/megahit/src/sequence/io/sequence_lib.cpp.s

.PHONY : libs/megahit/src/sequence/io/sequence_lib.s

# target to generate assembly for a file
libs/megahit/src/sequence/io/sequence_lib.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sequence/io/sequence_lib.cpp.s
.PHONY : libs/megahit/src/sequence/io/sequence_lib.cpp.s

libs/megahit/src/sorting/base_engine.o: libs/megahit/src/sorting/base_engine.cpp.o

.PHONY : libs/megahit/src/sorting/base_engine.o

# target to build an object file
libs/megahit/src/sorting/base_engine.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/base_engine.cpp.o
.PHONY : libs/megahit/src/sorting/base_engine.cpp.o

libs/megahit/src/sorting/base_engine.i: libs/megahit/src/sorting/base_engine.cpp.i

.PHONY : libs/megahit/src/sorting/base_engine.i

# target to preprocess a source file
libs/megahit/src/sorting/base_engine.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/base_engine.cpp.i
.PHONY : libs/megahit/src/sorting/base_engine.cpp.i

libs/megahit/src/sorting/base_engine.s: libs/megahit/src/sorting/base_engine.cpp.s

.PHONY : libs/megahit/src/sorting/base_engine.s

# target to generate assembly for a file
libs/megahit/src/sorting/base_engine.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/base_engine.cpp.s
.PHONY : libs/megahit/src/sorting/base_engine.cpp.s

libs/megahit/src/sorting/kmer_counter.o: libs/megahit/src/sorting/kmer_counter.cpp.o

.PHONY : libs/megahit/src/sorting/kmer_counter.o

# target to build an object file
libs/megahit/src/sorting/kmer_counter.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmer_counter.cpp.o
.PHONY : libs/megahit/src/sorting/kmer_counter.cpp.o

libs/megahit/src/sorting/kmer_counter.i: libs/megahit/src/sorting/kmer_counter.cpp.i

.PHONY : libs/megahit/src/sorting/kmer_counter.i

# target to preprocess a source file
libs/megahit/src/sorting/kmer_counter.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmer_counter.cpp.i
.PHONY : libs/megahit/src/sorting/kmer_counter.cpp.i

libs/megahit/src/sorting/kmer_counter.s: libs/megahit/src/sorting/kmer_counter.cpp.s

.PHONY : libs/megahit/src/sorting/kmer_counter.s

# target to generate assembly for a file
libs/megahit/src/sorting/kmer_counter.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmer_counter.cpp.s
.PHONY : libs/megahit/src/sorting/kmer_counter.cpp.s

libs/megahit/src/sorting/kmsort_selector.o: libs/megahit/src/sorting/kmsort_selector.cpp.o

.PHONY : libs/megahit/src/sorting/kmsort_selector.o

# target to build an object file
libs/megahit/src/sorting/kmsort_selector.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmsort_selector.cpp.o
.PHONY : libs/megahit/src/sorting/kmsort_selector.cpp.o

libs/megahit/src/sorting/kmsort_selector.i: libs/megahit/src/sorting/kmsort_selector.cpp.i

.PHONY : libs/megahit/src/sorting/kmsort_selector.i

# target to preprocess a source file
libs/megahit/src/sorting/kmsort_selector.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmsort_selector.cpp.i
.PHONY : libs/megahit/src/sorting/kmsort_selector.cpp.i

libs/megahit/src/sorting/kmsort_selector.s: libs/megahit/src/sorting/kmsort_selector.cpp.s

.PHONY : libs/megahit/src/sorting/kmsort_selector.s

# target to generate assembly for a file
libs/megahit/src/sorting/kmsort_selector.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/kmsort_selector.cpp.s
.PHONY : libs/megahit/src/sorting/kmsort_selector.cpp.s

libs/megahit/src/sorting/read_to_sdbg_s1.o: libs/megahit/src/sorting/read_to_sdbg_s1.cpp.o

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.o

# target to build an object file
libs/megahit/src/sorting/read_to_sdbg_s1.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s1.cpp.o
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.cpp.o

libs/megahit/src/sorting/read_to_sdbg_s1.i: libs/megahit/src/sorting/read_to_sdbg_s1.cpp.i

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.i

# target to preprocess a source file
libs/megahit/src/sorting/read_to_sdbg_s1.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s1.cpp.i
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.cpp.i

libs/megahit/src/sorting/read_to_sdbg_s1.s: libs/megahit/src/sorting/read_to_sdbg_s1.cpp.s

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.s

# target to generate assembly for a file
libs/megahit/src/sorting/read_to_sdbg_s1.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s1.cpp.s
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s1.cpp.s

libs/megahit/src/sorting/read_to_sdbg_s2.o: libs/megahit/src/sorting/read_to_sdbg_s2.cpp.o

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.o

# target to build an object file
libs/megahit/src/sorting/read_to_sdbg_s2.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s2.cpp.o
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.cpp.o

libs/megahit/src/sorting/read_to_sdbg_s2.i: libs/megahit/src/sorting/read_to_sdbg_s2.cpp.i

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.i

# target to preprocess a source file
libs/megahit/src/sorting/read_to_sdbg_s2.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s2.cpp.i
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.cpp.i

libs/megahit/src/sorting/read_to_sdbg_s2.s: libs/megahit/src/sorting/read_to_sdbg_s2.cpp.s

.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.s

# target to generate assembly for a file
libs/megahit/src/sorting/read_to_sdbg_s2.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/read_to_sdbg_s2.cpp.s
.PHONY : libs/megahit/src/sorting/read_to_sdbg_s2.cpp.s

libs/megahit/src/sorting/seq_to_sdbg.o: libs/megahit/src/sorting/seq_to_sdbg.cpp.o

.PHONY : libs/megahit/src/sorting/seq_to_sdbg.o

# target to build an object file
libs/megahit/src/sorting/seq_to_sdbg.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/seq_to_sdbg.cpp.o
.PHONY : libs/megahit/src/sorting/seq_to_sdbg.cpp.o

libs/megahit/src/sorting/seq_to_sdbg.i: libs/megahit/src/sorting/seq_to_sdbg.cpp.i

.PHONY : libs/megahit/src/sorting/seq_to_sdbg.i

# target to preprocess a source file
libs/megahit/src/sorting/seq_to_sdbg.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/seq_to_sdbg.cpp.i
.PHONY : libs/megahit/src/sorting/seq_to_sdbg.cpp.i

libs/megahit/src/sorting/seq_to_sdbg.s: libs/megahit/src/sorting/seq_to_sdbg.cpp.s

.PHONY : libs/megahit/src/sorting/seq_to_sdbg.s

# target to generate assembly for a file
libs/megahit/src/sorting/seq_to_sdbg.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/sorting/seq_to_sdbg.cpp.s
.PHONY : libs/megahit/src/sorting/seq_to_sdbg.cpp.s

libs/megahit/src/tools/contigs_to_fastg.o: libs/megahit/src/tools/contigs_to_fastg.cpp.o

.PHONY : libs/megahit/src/tools/contigs_to_fastg.o

# target to build an object file
libs/megahit/src/tools/contigs_to_fastg.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/contigs_to_fastg.cpp.o
.PHONY : libs/megahit/src/tools/contigs_to_fastg.cpp.o

libs/megahit/src/tools/contigs_to_fastg.i: libs/megahit/src/tools/contigs_to_fastg.cpp.i

.PHONY : libs/megahit/src/tools/contigs_to_fastg.i

# target to preprocess a source file
libs/megahit/src/tools/contigs_to_fastg.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/contigs_to_fastg.cpp.i
.PHONY : libs/megahit/src/tools/contigs_to_fastg.cpp.i

libs/megahit/src/tools/contigs_to_fastg.s: libs/megahit/src/tools/contigs_to_fastg.cpp.s

.PHONY : libs/megahit/src/tools/contigs_to_fastg.s

# target to generate assembly for a file
libs/megahit/src/tools/contigs_to_fastg.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/contigs_to_fastg.cpp.s
.PHONY : libs/megahit/src/tools/contigs_to_fastg.cpp.s

libs/megahit/src/tools/filter_by_len.o: libs/megahit/src/tools/filter_by_len.cpp.o

.PHONY : libs/megahit/src/tools/filter_by_len.o

# target to build an object file
libs/megahit/src/tools/filter_by_len.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/filter_by_len.cpp.o
.PHONY : libs/megahit/src/tools/filter_by_len.cpp.o

libs/megahit/src/tools/filter_by_len.i: libs/megahit/src/tools/filter_by_len.cpp.i

.PHONY : libs/megahit/src/tools/filter_by_len.i

# target to preprocess a source file
libs/megahit/src/tools/filter_by_len.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/filter_by_len.cpp.i
.PHONY : libs/megahit/src/tools/filter_by_len.cpp.i

libs/megahit/src/tools/filter_by_len.s: libs/megahit/src/tools/filter_by_len.cpp.s

.PHONY : libs/megahit/src/tools/filter_by_len.s

# target to generate assembly for a file
libs/megahit/src/tools/filter_by_len.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/filter_by_len.cpp.s
.PHONY : libs/megahit/src/tools/filter_by_len.cpp.s

libs/megahit/src/tools/read_stat.o: libs/megahit/src/tools/read_stat.cpp.o

.PHONY : libs/megahit/src/tools/read_stat.o

# target to build an object file
libs/megahit/src/tools/read_stat.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/read_stat.cpp.o
.PHONY : libs/megahit/src/tools/read_stat.cpp.o

libs/megahit/src/tools/read_stat.i: libs/megahit/src/tools/read_stat.cpp.i

.PHONY : libs/megahit/src/tools/read_stat.i

# target to preprocess a source file
libs/megahit/src/tools/read_stat.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/read_stat.cpp.i
.PHONY : libs/megahit/src/tools/read_stat.cpp.i

libs/megahit/src/tools/read_stat.s: libs/megahit/src/tools/read_stat.cpp.s

.PHONY : libs/megahit/src/tools/read_stat.s

# target to generate assembly for a file
libs/megahit/src/tools/read_stat.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/tools/read_stat.cpp.s
.PHONY : libs/megahit/src/tools/read_stat.cpp.s

libs/megahit/src/utils/options_description.o: libs/megahit/src/utils/options_description.cpp.o

.PHONY : libs/megahit/src/utils/options_description.o

# target to build an object file
libs/megahit/src/utils/options_description.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/utils/options_description.cpp.o
.PHONY : libs/megahit/src/utils/options_description.cpp.o

libs/megahit/src/utils/options_description.i: libs/megahit/src/utils/options_description.cpp.i

.PHONY : libs/megahit/src/utils/options_description.i

# target to preprocess a source file
libs/megahit/src/utils/options_description.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/utils/options_description.cpp.i
.PHONY : libs/megahit/src/utils/options_description.cpp.i

libs/megahit/src/utils/options_description.s: libs/megahit/src/utils/options_description.cpp.s

.PHONY : libs/megahit/src/utils/options_description.s

# target to generate assembly for a file
libs/megahit/src/utils/options_description.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/libs/megahit/src/utils/options_description.cpp.s
.PHONY : libs/megahit/src/utils/options_description.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mcaat.dir/build.make CMakeFiles/mcaat.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mcaat"
	@echo "... libs/megahit/src/assembly/bubble_remover.o"
	@echo "... libs/megahit/src/assembly/bubble_remover.i"
	@echo "... libs/megahit/src/assembly/bubble_remover.s"
	@echo "... libs/megahit/src/assembly/contig_output.o"
	@echo "... libs/megahit/src/assembly/contig_output.i"
	@echo "... libs/megahit/src/assembly/contig_output.s"
	@echo "... libs/megahit/src/assembly/low_depth_remover.o"
	@echo "... libs/megahit/src/assembly/low_depth_remover.i"
	@echo "... libs/megahit/src/assembly/low_depth_remover.s"
	@echo "... libs/megahit/src/assembly/sdbg_pruning.o"
	@echo "... libs/megahit/src/assembly/sdbg_pruning.i"
	@echo "... libs/megahit/src/assembly/sdbg_pruning.s"
	@echo "... libs/megahit/src/assembly/tip_remover.o"
	@echo "... libs/megahit/src/assembly/tip_remover.i"
	@echo "... libs/megahit/src/assembly/tip_remover.s"
	@echo "... libs/megahit/src/assembly/unitig_graph.o"
	@echo "... libs/megahit/src/assembly/unitig_graph.i"
	@echo "... libs/megahit/src/assembly/unitig_graph.s"
	@echo "... libs/megahit/src/assembly/weak_link_remover.o"
	@echo "... libs/megahit/src/assembly/weak_link_remover.i"
	@echo "... libs/megahit/src/assembly/weak_link_remover.s"
	@echo "... libs/megahit/src/idba/contig_graph.o"
	@echo "... libs/megahit/src/idba/contig_graph.i"
	@echo "... libs/megahit/src/idba/contig_graph.s"
	@echo "... libs/megahit/src/idba/contig_graph_branch_group.o"
	@echo "... libs/megahit/src/idba/contig_graph_branch_group.i"
	@echo "... libs/megahit/src/idba/contig_graph_branch_group.s"
	@echo "... libs/megahit/src/idba/hash_graph.o"
	@echo "... libs/megahit/src/idba/hash_graph.i"
	@echo "... libs/megahit/src/idba/hash_graph.s"
	@echo "... libs/megahit/src/idba/sequence.o"
	@echo "... libs/megahit/src/idba/sequence.i"
	@echo "... libs/megahit/src/idba/sequence.s"
	@echo "... libs/megahit/src/localasm/hash_mapper.o"
	@echo "... libs/megahit/src/localasm/hash_mapper.i"
	@echo "... libs/megahit/src/localasm/hash_mapper.s"
	@echo "... libs/megahit/src/localasm/local_assemble.o"
	@echo "... libs/megahit/src/localasm/local_assemble.i"
	@echo "... libs/megahit/src/localasm/local_assemble.s"
	@echo "... libs/megahit/src/sdbg/sdbg_meta.o"
	@echo "... libs/megahit/src/sdbg/sdbg_meta.i"
	@echo "... libs/megahit/src/sdbg/sdbg_meta.s"
	@echo "... libs/megahit/src/sdbg/sdbg_raw_content.o"
	@echo "... libs/megahit/src/sdbg/sdbg_raw_content.i"
	@echo "... libs/megahit/src/sdbg/sdbg_raw_content.s"
	@echo "... libs/megahit/src/sdbg/sdbg_writer.o"
	@echo "... libs/megahit/src/sdbg/sdbg_writer.i"
	@echo "... libs/megahit/src/sdbg/sdbg_writer.s"
	@echo "... libs/megahit/src/sequence/io/fastx_reader.o"
	@echo "... libs/megahit/src/sequence/io/fastx_reader.i"
	@echo "... libs/megahit/src/sequence/io/fastx_reader.s"
	@echo "... libs/megahit/src/sequence/io/paired_fastx_reader.o"
	@echo "... libs/megahit/src/sequence/io/paired_fastx_reader.i"
	@echo "... libs/megahit/src/sequence/io/paired_fastx_reader.s"
	@echo "... libs/megahit/src/sequence/io/sequence_lib.o"
	@echo "... libs/megahit/src/sequence/io/sequence_lib.i"
	@echo "... libs/megahit/src/sequence/io/sequence_lib.s"
	@echo "... libs/megahit/src/sorting/base_engine.o"
	@echo "... libs/megahit/src/sorting/base_engine.i"
	@echo "... libs/megahit/src/sorting/base_engine.s"
	@echo "... libs/megahit/src/sorting/kmer_counter.o"
	@echo "... libs/megahit/src/sorting/kmer_counter.i"
	@echo "... libs/megahit/src/sorting/kmer_counter.s"
	@echo "... libs/megahit/src/sorting/kmsort_selector.o"
	@echo "... libs/megahit/src/sorting/kmsort_selector.i"
	@echo "... libs/megahit/src/sorting/kmsort_selector.s"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s1.o"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s1.i"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s1.s"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s2.o"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s2.i"
	@echo "... libs/megahit/src/sorting/read_to_sdbg_s2.s"
	@echo "... libs/megahit/src/sorting/seq_to_sdbg.o"
	@echo "... libs/megahit/src/sorting/seq_to_sdbg.i"
	@echo "... libs/megahit/src/sorting/seq_to_sdbg.s"
	@echo "... libs/megahit/src/tools/contigs_to_fastg.o"
	@echo "... libs/megahit/src/tools/contigs_to_fastg.i"
	@echo "... libs/megahit/src/tools/contigs_to_fastg.s"
	@echo "... libs/megahit/src/tools/filter_by_len.o"
	@echo "... libs/megahit/src/tools/filter_by_len.i"
	@echo "... libs/megahit/src/tools/filter_by_len.s"
	@echo "... libs/megahit/src/tools/read_stat.o"
	@echo "... libs/megahit/src/tools/read_stat.i"
	@echo "... libs/megahit/src/tools/read_stat.s"
	@echo "... libs/megahit/src/utils/options_description.o"
	@echo "... libs/megahit/src/utils/options_description.i"
	@echo "... libs/megahit/src/utils/options_description.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

