/**
 * @file buckets.h
 * @brief HMM profile size buckets (auto-generated from profiles/*.hmm)
 * 
 * This file is AUTO-GENERATED by generate_buckets.py
 * DO NOT EDIT MANUALLY - your changes will be overwritten
 * 
 * Contains size ranges for all HMM profiles based on LENG values.
 * Size range: -15% to +25% of LENG value
 */

#ifndef INCLUDE_BUCKETS_H_
#define INCLUDE_BUCKETS_H_

#include <string>
#include <vector>
#include <cstdint>

namespace HMMProfiles {

/**
 * @brief HMM profile size information
 */
struct ProfileSize {
    std::string filename;
    int leng;       // LENG value from HMM file
    int min_aa;     // Minimum amino acids (-15%)
    int max_aa;     // Maximum amino acids (+25%)
    int min_bp;     // Minimum base pairs (min_aa * 3)
    int max_bp;     // Maximum base pairs (max_aa * 3)
};



/**
 * @brief All HMM profiles with size ranges
 */
static const std::vector<ProfileSize> ALL_PROFILES = {
    {"Cas5_0_I.hmm", 43, 36, 53, 108, 159},
    {"MerR_1_V-K.hmm", 69, 58, 86, 174, 258},
    {"Cas2_11_CAS-I-II-III-IV-V-VI.hmm", 71, 60, 88, 180, 264},
    {"Cas2_2_CAS-I-II-III-IV-V-VI.hmm", 79, 67, 98, 201, 294},
    {"Cas2_0_I-II-III-V.hmm", 83, 70, 103, 210, 309},
    {"Cas2_10_CAS-I-II-III-IV-V-VI.hmm", 86, 73, 107, 219, 321},
    {"2OG_1_CAS-I-II-III-IV-V-VI.hmm", 94, 79, 117, 237, 351},
    {"Cas6_15_CAS-I-II-III-IV-V-VI.hmm", 112, 95, 140, 285, 420},
    {"Cas10_1_IIIB.hmm", 116, 98, 145, 294, 435},
    {"Cmr5gr11_14_CAS-III-B.hmm", 118, 100, 147, 300, 441},
    {"Csa3_1_CAS-I-II-III-IV-V-VI.hmm", 118, 100, 147, 300, 441},
    {"Cas10_1_CAS-III-B.hmm", 121, 102, 151, 306, 453},
    {"PrimPol_1_CAS-I-II-III-IV-V-VI.hmm", 130, 110, 162, 330, 486},
    {"TniQ_0_CAS-I-F.hmm", 139, 118, 173, 354, 519},
    {"Cse2gr11_1_CAS-I-E.hmm", 143, 121, 178, 363, 534},
    {"Cse2gr11_7_CAS-I-E.hmm", 144, 122, 180, 366, 540},
    {"Cas6_13_CAS-I-II-III-IV-V-VI.hmm", 151, 128, 188, 384, 564},
    {"DEDDh_0_CAS-I-II-III-IV-V-VI.hmm", 160, 136, 200, 408, 600},
    {"WYL_3_CAS-I-II-III-IV-V-VI.hmm", 172, 146, 215, 438, 645},
    {"Cas3_1_I.hmm", 178, 151, 222, 453, 666},
    {"Csm3_0_IIID.hmm", 178, 151, 222, 453, 666},
    {"Cas5_1_CAS-I-E.hmm", 180, 153, 225, 459, 675},
    {"Csm3gr7_2_CAS-III-A-III-D.hmm", 180, 153, 225, 459, 675},
    {"Cas5_0_CAS-I-E.hmm", 182, 154, 227, 462, 681},
    {"Cas6f_2_CAS-I-II-III-IV-V-VI.hmm", 185, 157, 231, 471, 693},
    {"Csm3_1_IIIAD.hmm", 189, 160, 236, 480, 708},
    {"Cas6_0_CAS-I-II-III-IV-V-VI.hmm", 194, 164, 242, 492, 726},
    {"Csm3gr7_12_CAS-III-A-III-D.hmm", 199, 169, 248, 507, 744},
    {"Cas6_0_I-III.hmm", 200, 170, 250, 510, 750},
    {"Cas5_0_CAS-I.hmm", 201, 170, 251, 510, 753},
    {"Cas6e_2_CAS-I-II-III-IV-V-VI.hmm", 202, 171, 252, 513, 756},
    {"Cas3HD_0_CAS-I.hmm", 203, 172, 253, 516, 759},
    {"Cas6e_1_CAS-I-II-III-IV-V-VI.hmm", 212, 180, 265, 540, 795},
    {"Cas5_2_CAS-I.hmm", 213, 181, 266, 543, 798},
    {"RT_0_CAS-I-II-III-IV-V-VI.hmm", 213, 181, 266, 543, 798},
    {"Csf3_0_IV.hmm", 222, 188, 277, 564, 831},
    {"Cas7b_0_CAS-I-B-I-C.hmm", 254, 215, 317, 645, 951},
    {"Cas1_8_CAS-I-II-III-IV-V-VI.hmm", 283, 240, 353, 720, 1059},
    {"RT_0_CAS-III-AM-III-B.hmm", 298, 253, 372, 759, 1116},
    {"Cas1_0_I-II-III-V.hmm", 315, 267, 393, 801, 1179},
    {"Cas1_0_CAS-I-II-III-IV-V-VI.hmm", 317, 269, 396, 807, 1188},
    {"Cas6_10_CAS-I-II-III-IV-V-VI.hmm", 322, 273, 402, 819, 1206},
    {"Csf2_0_IV.hmm", 329, 279, 411, 837, 1233},
    {"Cas7_1_CAS-I-E.hmm", 359, 305, 448, 915, 1344},
    {"Csx1_18_CAS-III.hmm", 376, 319, 470, 957, 1410},
    {"TnpB_0_Competitive.hmm", 400, 340, 500, 1020, 1500},
    {"TnpB_1_Competitive.hmm", 409, 347, 511, 1041, 1533},
    {"Csx1_12_CAS-III.hmm", 425, 361, 531, 1083, 1593},
    {"Cas12f1_2_CAS-V-F.hmm", 429, 364, 536, 1092, 1608},
    {"Cas8e_4_CAS-I-E.hmm", 465, 395, 581, 1185, 1743},
    {"Cas8e_1_CAS-I-E.hmm", 474, 402, 592, 1206, 1776},
    {"Cmr6gr7_0_CAS-III-B-III-C.hmm", 544, 462, 680, 1386, 2040},
    {"Cas8c_3_CAS-I-C.hmm", 559, 475, 698, 1425, 2094},
    {"Cas9_0_II-D.hmm", 853, 725, 1066, 2175, 3198},
    {"Cas12a_0_CAS-V-A.hmm", 1244, 1057, 1555, 3171, 4665},
};



/**
 * @brief Overall size range constants
 */
constexpr int MIN_PROFILE_AA = 36;
constexpr int MAX_PROFILE_AA = 1555;
constexpr int MIN_PROFILE_BP = 108;
constexpr int MAX_PROFILE_BP = 4665;
constexpr int TOTAL_PROFILES = 55;

/**
 * @brief Utility for filtering HMM profiles based on size criteria
 */
struct HMMPicker {
    /**
     * @brief Filter profiles by base pair length
     * @param L Target length in base pairs
     * @return Vector of ProfileSize entries where min_bp < L < max_bp
     */
    static std::vector<ProfileSize> filterByLength(int L) {
        std::vector<ProfileSize> result;
        result.reserve(100);  // Reserve space to avoid reallocations
        for (const auto& profile : ALL_PROFILES) {
            if (profile.min_bp <= L && L <= profile.max_bp) {
                result.push_back(profile);
            }
        }
        
        return result;
    }
    
    /**
     * @brief Get the minimum ORF length across all profiles
     * @return Minimum min_bp value from all profiles
     */
    static int getMinimumORFLength() {
        if (ALL_PROFILES.empty()) return 0;
        
        int min_length = ALL_PROFILES[0].min_bp;
        for (const auto& profile : ALL_PROFILES) {
            if (profile.min_bp < min_length) {
                min_length = profile.min_bp;
            }
        }
        
        return min_length;
    }
};

}  // namespace HMMProfiles

#endif  // INCLUDE_BUCKETS_H_
