/**
 * @file buckets.h
 * @brief HMM profile size buckets (auto-generated from profiles/*.hmm)
 * 
 * This file is AUTO-GENERATED by generate_buckets.py
 * DO NOT EDIT MANUALLY - your changes will be overwritten
 * 
 * Contains size ranges for all HMM profiles based on LENG values.
 * Size range: -15% to +25% of LENG value
 */

#ifndef INCLUDE_BUCKETS_H_
#define INCLUDE_BUCKETS_H_

#include <string>
#include <vector>
#include <cstdint>

namespace HMMProfiles {

/**
 * @brief HMM profile size information
 */
struct ProfileSize {
    std::string filename;
    int leng;       // LENG value from HMM file
    int min_aa;     // Minimum amino acids (-15%)
    int max_aa;     // Maximum amino acids (+25%)
    int min_bp;     // Minimum base pairs (min_aa * 3)
    int max_bp;     // Maximum base pairs (max_aa * 3)
};



/**
 * @brief All HMM profiles with size ranges
 */
static const std::vector<ProfileSize> ALL_PROFILES = {
    {"Cas5_0_I.hmm", 43, 36, 53, 108, 159},
    {"Cas2_3_CAS-I-II-III-IV-V-VI.hmm", 62, 52, 77, 156, 231},
    {"MerR_1_V-K.hmm", 69, 58, 86, 174, 258},
    {"Cas2_11_CAS-I-II-III-IV-V-VI.hmm", 71, 60, 88, 180, 264},
    {"Cas2_2_CAS-I-II-III-IV-V-VI.hmm", 79, 67, 98, 201, 294},
    {"Cas2_0_I-II-III-V.hmm", 83, 70, 103, 210, 309},
    {"Cas2_10_CAS-I-II-III-IV-V-VI.hmm", 86, 73, 107, 219, 321},
    {"2OG_1_CAS-I-II-III-IV-V-VI.hmm", 94, 79, 117, 237, 351},
    {"Cas2_8_CAS-I-II-III-IV-V-VI.hmm", 101, 85, 126, 255, 378},
    {"Cas2_9_CAS-I-II-III-IV-V-VI.hmm", 101, 85, 126, 255, 378},
    {"Csm2gr11_7_CAS-III-A.hmm", 110, 93, 137, 279, 411},
    {"Cas6_15_CAS-I-II-III-IV-V-VI.hmm", 112, 95, 140, 285, 420},
    {"Cas10_1_IIIB.hmm", 116, 98, 145, 294, 435},
    {"Cmr5gr11_14_CAS-III-B.hmm", 118, 100, 147, 300, 441},
    {"Csa3_1_CAS-I-II-III-IV-V-VI.hmm", 118, 100, 147, 300, 441},
    {"Cas10_1_CAS-III-B.hmm", 121, 102, 151, 306, 453},
    {"Cmr5gr11_0_CAS-III-C.hmm", 127, 107, 158, 321, 474},
    {"PD_DExK_2_CAS-I-II-III-IV-V-VI.hmm", 127, 107, 158, 321, 474},
    {"Cmr5_0_IIIC.hmm", 129, 109, 161, 327, 483},
    {"PrimPol_1_CAS-I-II-III-IV-V-VI.hmm", 130, 110, 162, 330, 486},
    {"Cmr5gr11_9_CAS-III-B.hmm", 137, 116, 171, 348, 513},
    {"TniQ_0_CAS-I-F.hmm", 139, 118, 173, 354, 519},
    {"Cse2gr11_1_CAS-I-E.hmm", 143, 121, 178, 363, 534},
    {"Cse2gr11_7_CAS-I-E.hmm", 144, 122, 180, 366, 540},
    {"Csm2_0_IIID.hmm", 148, 125, 185, 375, 555},
    {"Csm2gr11_1_CAS-III-D.hmm", 149, 126, 186, 378, 558},
    {"Cas6_13_CAS-I-II-III-IV-V-VI.hmm", 151, 128, 188, 384, 564},
    {"DEDDh_0_CAS-I-II-III-IV-V-VI.hmm", 160, 136, 200, 408, 600},
    {"Cas4_5_CAS-I-II-III-IV-V-VI.hmm", 161, 136, 201, 408, 603},
    {"Cas13a_0_CAS-VI-A.hmm", 165, 140, 206, 420, 618},
    {"Cas13a_0_VIA.hmm", 167, 141, 208, 423, 624},
    {"Csb1gr7_0_CAS-I-U.hmm", 169, 143, 211, 429, 633},
    {"Cas11b_0_CAS-I-B.hmm", 170, 144, 212, 432, 636},
    {"WYL_3_CAS-I-II-III-IV-V-VI.hmm", 172, 146, 215, 438, 645},
    {"Cas3_1_I.hmm", 178, 151, 222, 453, 666},
    {"Csm3_0_IIID.hmm", 178, 151, 222, 453, 666},
    {"Cas5_0_CAS-I-A.hmm", 179, 152, 223, 456, 669},
    {"Cas5_1_CAS-I-E.hmm", 180, 153, 225, 459, 675},
    {"Csm3gr7_2_CAS-III-A-III-D.hmm", 180, 153, 225, 459, 675},
    {"Cas5_0_CAS-I-E.hmm", 182, 154, 227, 462, 681},
    {"tm_HEPN_0_CAS-VI-B.hmm", 183, 155, 228, 465, 684},
    {"Csm6_2_CAS-III.hmm", 184, 156, 230, 468, 690},
    {"Cas6f_1_CAS-I-II-III-IV-V-VI.hmm", 185, 157, 231, 471, 693},
    {"Cas6f_2_CAS-I-II-III-IV-V-VI.hmm", 185, 157, 231, 471, 693},
    {"Csm3_1_IIIAD.hmm", 189, 160, 236, 480, 708},
    {"Cas5_9_CAS-I-B.hmm", 190, 161, 237, 483, 711},
    {"Cas6_14_CAS-I-II-III-IV-V-VI.hmm", 190, 161, 237, 483, 711},
    {"Cas6_0_CAS-I-II-III-IV-V-VI.hmm", 194, 164, 242, 492, 726},
    {"Cas4_3_CAS-I-II-III-IV-V-VI.hmm", 197, 167, 246, 501, 738},
    {"Cas5_0_CAS-I-C.hmm", 198, 168, 247, 504, 741},
    {"Cas5_1_CAS-I-C.hmm", 198, 168, 247, 504, 741},
    {"Cse2gr11_5_CAS-I-E.hmm", 199, 169, 248, 507, 744},
    {"Csm3gr7_12_CAS-III-A-III-D.hmm", 199, 169, 248, 507, 744},
    {"Cas6_0_I-III.hmm", 200, 170, 250, 510, 750},
    {"Cas5_0_CAS-I.hmm", 201, 170, 251, 510, 753},
    {"Cas6e_2_CAS-I-II-III-IV-V-VI.hmm", 202, 171, 252, 513, 756},
    {"Cas3HD_0_CAS-I.hmm", 203, 172, 253, 516, 759},
    {"PD_DExK_1_CAS-I-II-III-IV-V-VI.hmm", 203, 172, 253, 516, 759},
    {"2OG_0_CAS-I-II-III-IV-V-VI.hmm", 205, 174, 256, 522, 768},
    {"Csx21_0_CAS-III-A-III-D.hmm", 210, 178, 262, 534, 786},
    {"Csx21_0_CAS-III-A.hmm", 210, 178, 262, 534, 786},
    {"Cas6e_1_CAS-I-II-III-IV-V-VI.hmm", 212, 180, 265, 540, 795},
    {"Cas5_2_CAS-I.hmm", 213, 181, 266, 543, 798},
    {"RT_0_CAS-I-II-III-IV-V-VI.hmm", 213, 181, 266, 543, 798},
    {"Cas6_5_CAS-I-II-III-IV-V-VI.hmm", 219, 186, 273, 558, 819},
    {"Cas5_0_CAS-I-B.hmm", 221, 187, 276, 561, 828},
    {"Csf3_0_IV.hmm", 222, 188, 277, 564, 831},
    {"Csn2_0_CAS-II-A.hmm", 223, 189, 278, 567, 834},
    {"Csf1_0_IV.hmm", 227, 192, 283, 576, 849},
    {"Cmr6gr7_3_CAS-III-B-III-C.hmm", 250, 212, 312, 636, 936},
    {"Cmr6_0_IIIC.hmm", 252, 214, 315, 642, 945},
    {"Cas7b_0_CAS-I-B-I-C.hmm", 254, 215, 317, 645, 951},
    {"CasR_0_CAS-III-B-III-D.hmm", 255, 216, 318, 648, 954},
    {"Csm5gr7_2_CAS-III-A-III-D.hmm", 258, 219, 322, 657, 966},
    {"Cas1_1_CAS-I-II-III-IV-V-VI.hmm", 261, 221, 326, 663, 978},
    {"Cas5f_0_CAS-I-F.hmm", 261, 221, 326, 663, 978},
    {"Cas7_3_CAS-I.hmm", 265, 225, 331, 675, 993},
    {"Csx3_2_CAS-I-III.hmm", 277, 235, 346, 705, 1038},
    {"Cas6_0_CAS-I-III-B.hmm", 282, 239, 352, 717, 1056},
    {"Cas1_8_CAS-I-II-III-IV-V-VI.hmm", 283, 240, 353, 720, 1059},
    {"Cmr3gr5_6_CAS-III-B-III-C.hmm", 285, 242, 356, 726, 1068},
    {"Cmr3_0_IIIC.hmm", 287, 243, 358, 729, 1074},
    {"Cas5f_2_CAS-I-F.hmm", 291, 247, 363, 741, 1089},
    {"Cas5f_3_CAS-I-F.hmm", 293, 249, 366, 747, 1098},
    {"RT_0_CAS-III-AM-III-B.hmm", 298, 253, 372, 759, 1116},
    {"Csx1_7_CAS-III.hmm", 309, 262, 386, 786, 1158},
    {"WYL_0_CAS-I-II-III-IV-V-VI.hmm", 313, 266, 391, 798, 1173},
    {"Cas1_0_I-II-III-V.hmm", 315, 267, 393, 801, 1179},
    {"Cas1_0_CAS-I-II-III-IV-V-VI.hmm", 317, 269, 396, 807, 1188},
    {"Csm4gr5_0_CAS-III-A-III-D.hmm", 317, 269, 396, 807, 1188},
    {"Cas1_6_CAS-I-II-III-IV-V-VI.hmm", 320, 272, 400, 816, 1200},
    {"Cas6_10_CAS-I-II-III-IV-V-VI.hmm", 322, 273, 402, 819, 1206},
    {"Cas7f_2_CAS-I-F.hmm", 326, 277, 407, 831, 1221},
    {"Cas1_0_I-II-III.hmm", 327, 277, 408, 831, 1224},
    {"Cas1_7_CAS-I-II-III-IV-V-VI.hmm", 328, 278, 410, 834, 1230},
    {"Csf2_0_IV.hmm", 329, 279, 411, 837, 1233},
    {"Cas7f_1_CAS-I-F.hmm", 331, 281, 413, 843, 1239},
    {"Csn2_8_CAS-II-A.hmm", 335, 284, 418, 852, 1254},
    {"Cas1_5_CAS-I-II-III-IV-V-VI.hmm", 338, 287, 422, 861, 1266},
    {"Cas1_0_IC.hmm", 340, 289, 425, 867, 1275},
    {"Cmr1gr7_5_CAS-III-B-III-C.hmm", 340, 289, 425, 867, 1275},
    {"Cas7_3_CAS-I-B.hmm", 351, 298, 438, 894, 1314},
    {"Cmr3_1_IIIB.hmm", 357, 303, 446, 909, 1338},
    {"Cmr3gr5_4_CAS-III-B-III-C.hmm", 358, 304, 447, 912, 1341},
    {"Cas7_1_CAS-I-E.hmm", 359, 305, 448, 915, 1344},
    {"Cas8f_7_CAS-I-F.hmm", 376, 319, 470, 957, 1410},
    {"Csx1_18_CAS-III.hmm", 376, 319, 470, 957, 1410},
    {"Cas8b2_0_CAS-I-B.hmm", 389, 330, 486, 990, 1458},
    {"TniQ_1_I-F.hmm", 400, 340, 500, 1020, 1500},
    {"TnpB_0_Competitive.hmm", 400, 340, 500, 1020, 1500},
    {"TnpB_1_Competitive.hmm", 409, 347, 511, 1041, 1533},
    {"Cas10_7_CAS-III.hmm", 410, 348, 512, 1044, 1536},
    {"Cas10_0_III.hmm", 414, 351, 517, 1053, 1551},
    {"Csx1_16_CAS-III.hmm", 420, 357, 525, 1071, 1575},
    {"Cas8f_0_CAS-I-F.hmm", 422, 358, 527, 1074, 1581},
    {"Csx1_12_CAS-III.hmm", 425, 361, 531, 1083, 1593},
    {"Cas12f1_2_CAS-V-F.hmm", 429, 364, 536, 1092, 1608},
    {"Cas8b6_0_CAS-I-B.hmm", 431, 366, 538, 1098, 1614},
    {"WYL_1_CAS-I-II-III-IV-V-VI.hmm", 462, 392, 577, 1176, 1731},
    {"WYL_2_CAS-I-II-III-IV-V-VI.hmm", 462, 392, 577, 1176, 1731},
    {"Cas8e_4_CAS-I-E.hmm", 465, 395, 581, 1185, 1743},
    {"Cas8e_1_CAS-I-E.hmm", 474, 402, 592, 1206, 1776},
    {"Cas12f2_2_CAS-V-F.hmm", 493, 419, 616, 1257, 1848},
    {"Cas12f3_0_CAS-V-F.hmm", 496, 421, 620, 1263, 1860},
    {"Cas10_0_CAS-III.hmm", 511, 434, 638, 1302, 1914},
    {"Csx1_14_CAS-III.hmm", 533, 453, 666, 1359, 1998},
    {"Cmr6gr7_0_CAS-III-B-III-C.hmm", 544, 462, 680, 1386, 2040},
    {"CorA_0_CAS-III-B-III-D.hmm", 551, 468, 688, 1404, 2064},
    {"Cas8b3_2_CAS-I-B.hmm", 557, 473, 696, 1419, 2088},
    {"Cas8c_3_CAS-I-C.hmm", 559, 475, 698, 1425, 2094},
    {"Cas8c_1_CAS-I-C.hmm", 570, 484, 712, 1452, 2136},
    {"Cas12m_0_V-M.hmm", 577, 490, 721, 1470, 2163},
    {"Cas8b1_13_CAS-I-B.hmm", 580, 493, 725, 1479, 2175},
    {"Cas8b1_8_CAS-I-B.hmm", 592, 503, 740, 1509, 2220},
    {"Csm3gr7_4_CAS-III-A-III-D.hmm", 640, 544, 800, 1632, 2400},
    {"Csm3_0_IIIAD.hmm", 650, 552, 812, 1656, 2436},
    {"Cas10_1_CAS-III.hmm", 654, 555, 817, 1665, 2451},
    {"Csf4_0_IVA.hmm", 666, 566, 832, 1698, 2496},
    {"CasR_0_CAS-III-D.hmm", 732, 622, 915, 1866, 2745},
    {"Cas3_1_CAS-I.hmm", 745, 633, 931, 1899, 2793},
    {"Cas9_0_II-D.hmm", 853, 725, 1066, 2175, 3198},
    {"Cas13d_0_CAS-VI-D.hmm", 929, 789, 1161, 2367, 3483},
    {"Cas9_0_II-C2.hmm", 967, 821, 1208, 2463, 3624},
    {"Cas13b_0_VIB1.hmm", 1097, 932, 1371, 2796, 4113},
    {"Cas13b_1_CAS-VI-B.hmm", 1101, 935, 1376, 2805, 4128},
    {"Cas12b1_0_CAS-V-B.hmm", 1125, 956, 1406, 2868, 4218},
    {"Cas12b_0_VB.hmm", 1130, 960, 1412, 2880, 4236},
    {"STAND_TPR_0_CAS-I-E.hmm", 1210, 1028, 1512, 3084, 4536},
    {"Cas12a_1_VA.hmm", 1233, 1048, 1541, 3144, 4623},
    {"Cas12a_0_CAS-V-A.hmm", 1244, 1057, 1555, 3171, 4665},
    {"Cas12c_0_CAS-V-C.hmm", 1272, 1081, 1590, 3243, 4770},
};



/**
 * @brief Overall size range constants
 */
constexpr int MIN_PROFILE_AA = 36;
constexpr int MAX_PROFILE_AA = 1590;
constexpr int MIN_PROFILE_BP = 108;
constexpr int MAX_PROFILE_BP = 4770;
constexpr int TOTAL_PROFILES = 151;

/**
 * @brief Utility for filtering HMM profiles based on size criteria
 */
struct HMMPicker {
    /**
     * @brief Filter profiles by base pair length
     * @param L Target length in base pairs
     * @return Vector of ProfileSize entries where min_bp < L < max_bp
     */
    static std::vector<ProfileSize> filterByLength(int L) {
        std::vector<ProfileSize> result;
        result.reserve(100);  // Reserve space to avoid reallocations
        for (const auto& profile : ALL_PROFILES) {
            if (profile.min_bp <= L && L <= profile.max_bp) {
                result.push_back(profile);
            }
        }
        
        return result;
    }
    
    /**
     * @brief Get the minimum ORF length across all profiles
     * @return Minimum min_bp value from all profiles
     */
    static int getMinimumORFLength() {
        if (ALL_PROFILES.empty()) return 0;
        
        int min_length = ALL_PROFILES[0].min_bp;
        for (const auto& profile : ALL_PROFILES) {
            if (profile.min_bp < min_length) {
                min_length = profile.min_bp;
            }
        }
        
        return min_length;
    }
};

}  // namespace HMMProfiles

#endif  // INCLUDE_BUCKETS_H_
